set(CMAKE_SYSTEM_NAME Preview1-threads)
set(CMAKE_SYSTEM_PROCESSOR wasm32)
set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET wasm32-wasi-preview1-threads)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET wasm32-wasi-preview1-threads)