set(CMAKE_SYSTEM_NAME Solaris)
set(CMAKE_SYSTEM_PROCESSOR sparcv9)
set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET sparcv9-sun-solaris)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET sparcv9-sun-solaris)