set(CMAKE_SYSTEM_NAME Androideabi)
set(CMAKE_SYSTEM_PROCESSOR thumbv7neon)
set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET thumbv7neon-linux-androideabi)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET thumbv7neon-linux-androideabi)