set(CMAKE_SYSTEM_NAME Eabi)
set(CMAKE_SYSTEM_PROCESSOR thumbv8m.base)
set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET thumbv8m.base-none-eabi)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET thumbv8m.base-none-eabi)