set(CMAKE_SYSTEM_NAME None-softfloat)
set(CMAKE_SYSTEM_PROCESSOR loongarch64)
set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET loongarch64-unknown-none-softfloat)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET loongarch64-unknown-none-softfloat)