set(CMAKE_SYSTEM_NAME Eabihf)
set(CMAKE_SYSTEM_PROCESSOR thumbv8m.main)
set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET thumbv8m.main-none-eabihf)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET thumbv8m.main-none-eabihf)