set(CMAKE_SYSTEM_NAME Linux-gnueabi)
set(CMAKE_SYSTEM_PROCESSOR armv5te)
set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET armv5te-unknown-linux-gnueabi)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET armv5te-unknown-linux-gnueabi)