
set(CMAKE_SYSTEM_NAME Eabi)
set(CMAKE_SYSTEM_PROCESSOR armv7r)
set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET armv7r-none-eabi)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET armv7r-none-eabi)
