set(CMAKE_SYSTEM_NAME Linux-gnu)
set(CMAKE_SYSTEM_PROCESSOR powerpc64le)
set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET powerpc64le-unknown-linux-gnu)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET powerpc64le-unknown-linux-gnu)