
set(CMAKE_SYSTEM_NAME Uefi)
set(CMAKE_SYSTEM_PROCESSOR i686)
set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET i686-unknown-uefi)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET i686-unknown-uefi)
