set(CMAKE_SYSTEM_NAME Linux-gnu)
set(CMAKE_SYSTEM_PROCESSOR sparc64)
set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET sparc64-unknown-linux-gnu)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET sparc64-unknown-linux-gnu)