set(CMAKE_SYSTEM_NAME Eabi)
set(CMAKE_SYSTEM_PROCESSOR thumbv7m)
set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET thumbv7m-none-eabi)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET thumbv7m-none-eabi)